# Generated by Django 5.1.4 on 2025-01-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_marketing',
            field=models.FloatField(default=0),
        ),
    ]
