# Generated by Django 5.1.4 on 2025-01-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_preco_marketing_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produto_imagens'),
        ),
    ]
