# Generated by Django 5.1.4 on 2025-02-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_categoria_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('tipo1', 'Moedas'), ('tipo2', 'Serviços'), ('tipo3', 'Gold'), ('tipo4', 'Outros')], default='tipo1', max_length=50, verbose_name='Tipo'),
        ),
    ]
