# Generated by Django 5.1.4 on 2025-01-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_remove_itempedido_preco_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='in_game_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
